# Generated by Django 2.0 on 2019-01-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnuCats',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_parent', models.PositiveIntegerField()),
                ('cat_priority', models.PositiveSmallIntegerField()),
                ('cat_show', models.IntegerField()),
                ('cat_locked', models.IntegerField()),
                ('cat_subd_geo', models.IntegerField()),
                ('cat_subd_type', models.IntegerField()),
                ('cat_color', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
