# Generated by Django 2.0 on 2019-01-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_auto_20190113_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annucats',
            options={'managed': False},
        ),
    ]
