# Generated by Django 2.0 on 2019-01-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0004_auto_20190113_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnuSite20181005',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=255)),
                ('site_url', models.CharField(max_length=255)),
                ('site_mail', models.CharField(max_length=100)),
                ('site_pr', models.PositiveIntegerField()),
                ('site_pr_lastchecked', models.PositiveIntegerField()),
                ('site_status', models.IntegerField()),
                ('site_dispmode', models.IntegerField()),
                ('site_reg_date', models.PositiveIntegerField()),
                ('site_valid_date', models.PositiveIntegerField()),
                ('site_mail_date', models.PositiveIntegerField()),
                ('site_dept', models.PositiveSmallIntegerField()),
                ('site_priority', models.IntegerField()),
                ('site_ip', models.CharField(max_length=15)),
                ('site_origine', models.PositiveIntegerField()),
                ('site_clics', models.BigIntegerField()),
                ('site_rss', models.CharField(max_length=255)),
                ('site_lien_retour', models.IntegerField()),
                ('site_vis_retours', models.BigIntegerField()),
                ('site_vis_retours_06', models.BigIntegerField()),
                ('site_is_officetourisme', models.IntegerField()),
                ('site_is_criteria', models.CharField(max_length=255)),
                ('site_is_1stpage', models.IntegerField()),
                ('site_residence', models.SmallIntegerField()),
                ('site_validator', models.CharField(max_length=50)),
                ('site_pagerank', models.IntegerField()),
                ('site_lien_retour_url', models.TextField()),
                ('site_paypal_txn', models.CharField(max_length=32)),
                ('site_type_inscr', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'annu_site_20181005',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnnuSiteAppartient',
            fields=[
                ('app_site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_cat_id', models.IntegerField()),
                ('app_priority', models.IntegerField()),
            ],
            options={
                'db_table': 'annu_site_appartient',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='annucats',
            table='annu_cats',
        ),
    ]
